### PR TITLE
Server changes necessary to get map POST and GET working.

### PR DESCRIPTION
**Pull request by joshherkness**
I've updated some of the server code, please take a look at it and merge in as soon as possible, since these are TEST breaking changes.

### CODE REVIEW

**Review by kdjohnson — APPROVED** [review]
Cannot create multiple maps for a user, but this can be fixed in another issue.

**Comment by joshherkness** [comment]
I think multiple maps can be created for a single user?

**Comment by kdjohnson** [comment]
OK. I'll try it again.

**Comment by kdjohnson** [comment]
I get the following error:
`Arguments: ('User object', '\n', 'Tried to save duplicate unique keys (E11000 duplicate key error collection: mydatabase.model index: email_1 dup key: { : null })')` When I try to create another map past the initial one.

**Comment by joshherkness** [comment]
On the python side?

**Comment by joshherkness** [comment]
Ya, my create map > submit > create map > submit is working just fine

**Comment by kdjohnson** [comment]
OK. Must just be my problem then.

**Comment by joshherkness** [comment]
Well maybe it isn't

**Comment by jjrobertson14** [comment]
The changes to server.py look fine, but I have no way of testing the endpoints without the tests.py file without taking a long time to figure out how to do it with postman.

**Comment by joshherkness** [comment]
That's good enough for me. I'm going to get this in so you guys can start figuring out how to test it.

**Pull request merged**
