### PR TITLE
Add nginx to map to correct URLs, run vue on port 8080 #233

### PR DESCRIPTION
**Pull request by kdjohnson**

### CODE REVIEW

**Review by joshherkness — APPROVED** [review]

**Comment by kdjohnson** [comment]
@joshherkness Did you try this?

**Comment by joshherkness** [comment]
Should I just expect the docker containers to build and everything to work?

**Comment by joshherkness** [comment]
Should this fix the refresh issue?

**Comment by kdjohnson** [comment]
You only need to rebuild the vue image. Yes, it should fix that.

**Comment by joshherkness** [comment]
It works as expected when I navigate to `localhost`. However, when I use `localhost:8080` (for example `http://localhost:8080/library`, I get page not found. Is this expected?

**Comment by kdjohnson** [comment]
Yes, it only serves up on port `80`. I have nginx port forward to `8080` for our routes. Is that OK?

**Comment by joshherkness** [comment]
Ya, that's fine. This is good to go then.

**Pull request merged**
