### PR TITLE
Add vuex actions and mutations for the session state.

### LINKED ISSUE #153: Vuex for session
- Create state to hold a single session for the currently authenticated user.
- Actions and mutations for:
  - Setting the current session
  - Removing the current session

### PR DESCRIPTION
**Pull request by joshherkness**
closes #153

### CODE REVIEW

**Comment by joshherkness** [comment]
Should we explicitly state all properties of the session in vuex, or is leaving it a raw object fine?

**Comment by kdjohnson** [comment]
Raw object should be fine.

**Comment by joshherkness** [comment]
Hmm.. So I wrote the whole other file, but it doesn't look like I added that to a commit. fml

**Comment by joshherkness** [comment]
@kdjohnson there we go, my bad

**Review by kdjohnson — APPROVED** [review]

**Pull request merged**
