### PR TITLE
implement new card design

### PR DESCRIPTION
**Pull request by kdjohnson**
The map name is not being displayed because it is not being stored at all currently.

### CODE REVIEW

**Comment by joshherkness** [comment]
Ya, I realized that too...

**Comment by kdjohnson** [comment]
Also, How do you want to handle the pass off to the editor on open? Like how do you want to receive the data?

**Comment by joshherkness** [comment]
Right now, the editor route takes an `id` param. I'm then using that param to query for the whole map again. If you want an example of this, take a look at the reroute on form submit within the create map modal.

**Comment by joshherkness** [comment]
Also, delete and edit modals require different parameters than what you currently have in this PR. Parameters for the modal are passed the same way that you currently have it, but require those specified in the `params` data object on each of the modals. (Delete takes `id` and `name` right now, and Edit takes `id`, `name`, and `color`).

**Comment by joshherkness** [comment]
Do we just want to program each of the modals to take in an entire mapData?

**Comment by kdjohnson** [comment]
I'll just pass the correct values they need.

**Comment by joshherkness** [comment]
We can refactor in the future

**Comment by kdjohnson** [comment]
Right.

**Review by joshherkness — APPROVED** [review]

**Comment by kdjohnson** [comment]
Added those props in.

**Comment by joshherkness** [comment]
I also added an `onSuccess` callback to each of the modals params, we can use to keep the list updated without making extra api calls, but I don't think we need this right now.

And for this to work, you're going to need #121 #122

**Comment by joshherkness** [comment]
It's probably a good time to tell you that I didn't test any of my code. Good luck!

**Comment by joshherkness** [comment]
Is stuff plugging together alright?

**Comment by kdjohnson** [comment]
There are a few errors in the Edit Modal.

**Comment by joshherkness** [comment]
Woops

**Comment by kdjohnson** [comment]
No big deal.

**Comment by kdjohnson** [comment]
Alright fixed up those errors, it works as well as it can at this point until those other endpoints get merged in.

**Comment by joshherkness** [comment]
Delete and update should now be working and merged into development.

Also, delete should be returning the id of the map that was deleted

**Comment by joshherkness** [comment]
Actually, that doesn't even matter in the current implementation of the delete modal

**Comment by kdjohnson** [comment]
OK, Edit and Delete don't work but I think those are just backend problems.

**Comment by joshherkness** [comment]
Good catch

**Comment by kdjohnson** [comment]
Also, this 
screen shot 2018-02-03 at 7 40 38 pm

**Comment by kdjohnson** [comment]
The color picker is being cut off the modal is too small 😞

**Comment by joshherkness** [comment]
Pic or it didn't happen

That's not happening on create map modal, is it?

**Comment by kdjohnson** [comment]
No, this is Edit.

**Comment by joshherkness** [comment]
And the modal cuts it off?

**Comment by kdjohnson** [comment]
Ya

**Comment by kdjohnson** [comment]
screen shot 2018-02-03 at 7 46 24 pm

**Comment by joshherkness** [comment]
Can we set `overflow: auto` on the actual modal element (not the editor component)?

**Comment by joshherkness** [comment]
Don't worry about it for now

**Comment by kdjohnson** [comment]
Alright.

**Comment by joshherkness** [comment]
Fixed it

**Comment by kdjohnson** [comment]
Cool cool.

**Comment by kdjohnson** [comment]
So the endpoints work now. Just not sure on how to make the events propagate across correctly for the frontend properly.

**Comment by kdjohnson** [comment]
Meaning not having to reload the page for the changes to be seen.

**Pull request merged**
