### PR TITLE
Home Page

### LINKED ISSUE #42: Home page
### Create a home page for our web application.

- Should have navigation bar at the top of the page.
- Since the user must be logged in to view this page, make it a protected route. (i.e. a user must be have a valid auth_token)
- Pull the user email and display it in the top right of the navigation bar.

### LINKED ISSUE #48: Create site wide navigation bar
### Create a site wide navigation bar

- Determine the best way to add a navigation bar to the site.
- Should contain the following within the navigation bar:
  - Text name of our project
  - Link to `/maps`  (disabled until the actual route is implemented)
  - Link to `/editor`
- **Note** that we don't want the navigation bar on the authentication pages.

### LINKED ISSUE #49: Add user management to navigation bar
### Add user management to navigation bar

**Blocked until #48 is completed**

- Implement a drop down menu on the right side of the navigation bar.
- Drop down text should displaythe current user email.
- Drop down items include:
  - Sign out (red text)

### PR DESCRIPTION
**Pull request by kdjohnson**
Closes #42 
Closes #48 
Closes #49

### CODE REVIEW

**Comment by kdjohnson** [comment]
@joshherkness I didn't add the navbar to the Editor. I figured it would be best to let you handle that since you will need to compensate for it in the render.

**Comment by joshherkness** [comment]
Shouldn't the home view just render all child routes inside of itself. this would prevent having to include the navbar on any page that we want it.

`/home/maps` would render home component with list component inside
`/home/editor` would render home component with editor component inside

Home component could look something like this.

```
<template>
  <navbar/>
  <child-route/>
</template>
```

**Comment by joshherkness** [comment]
https://router.vuejs.org/en/essentials/nested-routes.html

**Comment by kdjohnson** [comment]
@joshherkness Made some changes.

**Pull request merged**
