### PR TITLE
Begin restructure of routes and flatten components directory

### PR DESCRIPTION
**Pull request by joshherkness**

### CODE REVIEW

**Comment by joshherkness** [comment]
@kdjohnson let me know what you think of the changes in this PR. You can make any changes to them if you want.

**Comment by kdjohnson** [comment]
These look great. 👍

**Review by kdjohnson — APPROVED** [review]

**Comment by joshherkness** [comment]
Even the server file modifications? If you can just take a look at `server.py`, `decorators.py`, and `router/index.js` closely to make sure I didn't mess anything up, that would be amazing.

**Comment by kdjohnson** [comment]
Only thing is that going to http://localhost:8080/editor doesn't route you back to the login page if your not authenticated. Besides that, everything is working as expected and code looks good.

**Pull request merged**
