### PR TITLE
59 create map model

### PR DESCRIPTION
**Pull request by AnthonyHewins**
fairly straightforward

### CODE REVIEW

**Comment by joshherkness** [comment]
Hey, I merged current development branch into this, make sure that I didn't screw anything up in the merge. Also, take a look at some of the model changes I made.

**Review by jjrobertson14 — COMMENTED** [review]
When i try to run tests.py, I'm getting
"
NameError: name 'EnumField' is not defined
"
I ran 'pip install -r server/requirements.txt' too

**Comment by joshherkness** [comment]
Oh ya, I guess mongoengine doesn't have an EnumField. Change this to something like StringField(choices=['voxel']). I don't know any other way to do an enum type.

**Comment by joshherkness** [comment]
I can change it

**Comment by joshherkness** [comment]
Try that

**Review by joshherkness — APPROVED** [review]

**Comment by joshherkness** [comment]
@jjrobertson14 Merge this in once you give it the all clear

**Pull request merged**
