### PR TITLE
Remove negative space

### PR DESCRIPTION
**Pull request by joshherkness**
* Updated styles for map list and grid
* Add last modified date to map list and grid
* Add search feature to library
* Editor should now "cancel" edit on click+drag
* Updated styles for session manager

### CODE REVIEW

**Review by kdjohnson — DISMISSED** [review]
Looks real good!

**Review by kdjohnson — CHANGES_REQUESTED** [review]
`"moment": "^2.21.0"` needs to be added to the package.json file.

**Comment by joshherkness** [comment]
Good catch

**Comment by joshherkness** [comment]
There we go

**Review by kdjohnson — APPROVED** [review]

**Pull request merged**
