### PR TITLE
Create some test data maps that can be used to test perf.

### PR DESCRIPTION
**Pull request by joshherkness**

### CODE REVIEW

**Comment by nlferman** [comment]
This might be easier to just approve this first so I can look at the different files. Is the plan to add logic for seeing how the app responds when a different JSON is loaded?

**Comment by joshherkness** [comment]
No, for now I just wanted to get maps created so we can visually test out edge cases.

**Comment by joshherkness** [comment]
Right now, the unity application cannot load out edge case of 48x48 filled.

**Comment by nlferman** [comment]
Okay. So should I just approve the pull request, then?

**Comment by joshherkness** [comment]
If you want to.

**Review by nlferman — APPROVED** [review]

**Pull request merged**
