### PR TITLE
114 add wireframes to voxels

### PR DESCRIPTION
**Pull request by nlferman**
This is done, but is branched from the socket branch, since that hasn't been merged to development yet.

### CODE REVIEW

**Review by joshherkness — CHANGES_REQUESTED** [review]
Pull from development and fix merge conflicts first.

**Comment by joshherkness** [comment]
Is there a PR for the socket branch?

**Comment by joshherkness** [comment]
Is there any way you can separate the wireframe implementation from the socket implementation. I don't think we're ready to merge in any socket code just yet, but I would be willing to merge in your wireframe code.

**Review by AnthonyHewins — CHANGES_REQUESTED** [review]
yeah put the socket stuff in a different file than server.py. i will figure out how to manage that later.

**Comment by nlferman** [comment]
Okay, I put the socketio stuff in a new file called socketio.py. Let me know if there's any other issues.

**Comment by joshherkness** [comment]
Lol, can you resolve the conflicts again

**Comment by nlferman** [comment]
Is this good now?

**Review by joshherkness — APPROVED** [review]

**Comment by joshherkness** [comment]
@AnthonyHewins You good with this one?

**Pull request merged**
